export default [
  { name: "Argentine Stock Exchanges and Markets", _id: "BYMA", country: "Argentina", cc: "ARG", currency: "ARS" },
  { name: "Australian Securities Exchange", _id: "ASX", country: "Australia", cc: "AUS", currency: "AUD" },
  { name: "Vienna Stock Exchange", _id: "WB", country: "Austria", cc: "AUT", currency: "EUR" },
  { name: "Bahrain Stock Exchange", _id: "BHB", country: "Bahrain", cc: "BHR", currency: "BHD" },
  { name: "Dhaka Stock Exchange", _id: "DSE", country: "Bangladesh", cc: "BGD", currency: "BDT" },
  { name: "Brazil Stock Exchange", _id: "B3", country: "Brazil", cc: "BRA", currency: "BRL" },
  { name: "Canadian Securities Exchange", _id: "CSE", country: "Canada", cc: "CAN", currency: "CAD" },
  { name: "Toronto Stock Exchange", _id: "TSX", country: "Canada", cc: "CAN", currency: "CAD" },
  { name: "TSX Venture Exchange", _id: "TSXV", country: "Canada", cc: "CAN", currency: "CAD" },
  { name: "Santiago Stock Exchange", _id: "SSE", country: "Chile", cc: "CHL", currency: "CLP" },
  { name: "Shanghai Stock Exchange", _id: "SSE", country: "China", cc: "CHN", currency: "CNY" },
  { name: "Shenzhen Stock Exchange", _id: "SZSE", country: "China", cc: "CHN", currency: "CNY" },
  { name: "Colombia Stock Exchange", _id: "BVC", country: "Colombia", cc: "COL", currency: "COP" },
  { name: "Cyprus Stock Exchange", _id: "CSE", country: "Cyprus", cc: "CYP", currency: "EUR" },
  { name: "Prague Stock Exchange", _id: "PSECZ", country: "Czech Republic", cc: "CZE", currency: "CZK" },
  { name: "Copenhagen Stock Exchange", _id: "OMXCOP", country: "Denmark", cc: "DNK", currency: "DKK" },
  { name: "Egyptian Exchange", _id: "EGX", country: "Egypt", cc: "EGY", currency: "EGP" },
  { name: "Tallinn Stock Exchange", _id: "OMXTAL", country: "Estonia", cc: "EST", currency: "EUR" },
  { name: "Euronext NV", _id: "Euronext", country: "European Union", cc: "EU", currency: "EUR" },
  { name: "Helsinki Stock Exchange", _id: "OMXHEL", country: "Finland", cc: "FIN", currency: "EUR" },
  { name: "Berlin Stock Exchange", _id: "BER", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Deutsche Borse Xetra", _id: "XETR", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Dusseldorf Stock Exchange", _id: "DUS", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Frankfurt Stock Exchange", _id: "FWB", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Hamburg Stock Exchange", _id: "HAM", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Hannover Stock Exchange", _id: "HAN", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Munich Stock Exchange", _id: "MUN", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Stuttgart Stock Exchange", _id: "SWB", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Tradegate Exchange", _id: "Tradegate Exchange", country: "Germany", cc: "DEU", currency: "EUR" },
  { name: "Athens Stock Exchange", _id: "ATHEX", country: "Greece", cc: "GRC", currency: "EUR" },
  { name: "Hang Seng Indexes", _id: "HSI", country: "Hong Kong", cc: "HKG", currency: "HKD" },
  { name: "The Stock Exchange of Hong Kong", _id: "SEHK", country: "Hong Kong", cc: "HKG", currency: "HKD" },
  { name: "Budapest Stock Exchange", _id: "BET", country: "Hungary", cc: "HUN", currency: "HUF" },
  { name: "Iceland Stock Exchange", _id: "OMXICE", country: "Iceland", cc: "ISL", currency: "ISK" },
  { name: "Bombay Stock Exchange", _id: "BSE", country: "India", cc: "IND", currency: "INR" },
  { name: "Multi Commodity Exchange", _id: "MCX", country: "India", cc: "IND", currency: "INR" },
  { name: "National Stock Exchange of India", _id: "NSE", country: "India", cc: "IND", currency: "INR" },
  { name: "Indonesia Stock Exchange", _id: "IDX", country: "Indonesia", cc: "IDN", currency: "IDR" },
  { name: "Tel Aviv Stock Exchange", _id: "TASE", country: "Israel", cc: "ISR", currency: "ILS" },
  { name: "Nagoya Stock Exchange", _id: "NSE", country: "Japan", cc: "JPN", currency: "JPY" },
  { name: "Tokyo Commodity Exchange", _id: "TOCOM", country: "Japan", cc: "JPN", currency: "JPY" },
  { name: "Tokyo Stock Exchange", _id: "TSE", country: "Japan", cc: "JPN", currency: "JPY" },
  { name: "Nairobi Securities Exchange", _id: "NSE", country: "Kenya", cc: "KEN", currency: "KES" },
  { name: "Riga Stock Exchange", _id: "OMXRIG", country: "Latvia", cc: "LVA", currency: "EUR" },
  { name: "Vilnius Stock Exchange", _id: "OMXVIL", country: "Lithuania", cc: "LTU", currency: "EUR" },
  { name: "Luxembourg Stock Exchange", _id: "LuxSE", country: "Luxembourg", cc: "LUX", currency: "EUR" },
  { name: "Bursa Malaysia Berhad", _id: "MYX", country: "Malaysia", cc: "MYS", currency: "MYR" },
  { name: "Bolsa Institucional de Valores", _id: "BIVA", country: "Mexico", cc: "MEX", currency: "MXN" },
  { name: "Casablanca Stock Exchange", _id: "CSE", country: "Morocco", cc: "MAR", currency: "MAD" },
  { name: "New Zealand Exchange", _id: "NZX", country: "New Zealand", cc: "NZL", currency: "NZD" },
  { name: "Nigerian Stock Exchange", _id: "NSE", country: "Nigeria", cc: "NGA", currency: "NGN" },
  { name: "Oslo Stock Exchange", _id: "OSEBX", country: "Norway", cc: "NOR", currency: "NOK" },
  { name: "Pakistan Stock Exchange", _id: "PSX", country: "Pakistan", cc: "PAK", currency: "PKR" },
  { name: "Philippine Stock Exchange", _id: "PSE", country: "Philippines", cc: "PHL", currency: "PHP" },
  { name: "Warsaw Stock Exchange", _id: "GPW", country: "Poland", cc: "POL", currency: "PLN" },
  { name: "Qatar Stock Exchange", _id: "QSE", country: "Qatar", cc: "QAT", currency: "QAR" },
  { name: "Bucharest Stock Exchange", _id: "BVB", country: "Romania", cc: "ROU", currency: "RON" },
  { name: "Saudi Exchange", _id: "Tadawul", country: "Saudi Arabia", cc: "SAU", currency: "SAR" },
  { name: "Belgrade Stock Exchange", _id: "BELEX", country: "Serbia", cc: "SRB", currency: "RSD" },
  { name: "Singapore Exchange", _id: "SGX", country: "Singapore", cc: "SGP", currency: "SGD" },
  { name: "Bratislava Stock Exchange", _id: "BSSE", country: "Slovakia", cc: "SVK", currency: "EUR" },
  { name: "Johannesburg Stock Exchange", _id: "JSE", country: "South Africa", cc: "ZAF", currency: "ZAR" },
  { name: "Korea Stock Exchange", _id: "KRX", country: "South Korea", cc: "KOR", currency: "KRW" },
  { name: "Bolsa de Madrid", _id: "BME", country: "Spain", cc: "ESP", currency: "EUR" },
  { name: "Nordic Growth Market", _id: "NGM", country: "Sweden", cc: "SWE", currency: "SEK" },
  { name: "Stockholm Stock Exchange", _id: "OMXSTO", country: "Sweden", cc: "SWE", currency: "SEK" },
  { name: "BX Swiss", _id: "BX", country: "Switzerland", cc: "CHE", currency: "CHF" },
  { name: "SIX Swiss Exchange", _id: "SIX", country: "Switzerland", cc: "CHE", currency: "CHF" },
  { name: "Taipei Exchange", _id: "TPEx", country: "Taiwan", cc: "TWN", currency: "TWD" },
  { name: "Taiwan Stock Exchange", _id: "TWSE", country: "Taiwan", cc: "TWN", currency: "TWD" },
  { name: "Stock Exchange of Thailand", _id: "SET", country: "Thailand", cc: "THA", currency: "THB" },
  { name: "Tunis Stock Exchange", _id: "BVMT", country: "Tunisia", cc: "TUN", currency: "TND" },
  { name: "Borsa Istanbul", _id: "BIST", country: "Turkey", cc: "TUR", currency: "TRY" },
  { name: "Abu Dhabi Securities Exchange", _id: "ADX", country: "United Arab Emirates", cc: "ARE", currency: "AED" },
  { name: "Dubai Financial Market", _id: "DFM", country: "United Arab Emirates", cc: "ARE", currency: "AED" },
  { name: "NASDAQ Dubai", _id: "NASDAQDUBAI", country: "United Arab Emirates", cc: "ARE", currency: "AED" },
  { name: "London Stock Exchange", _id: "LSE", country: "United Kingdom", cc: "GB", currency: "GBP" },
  { name: "Turquoise", _id: "Turquoise", country: "United Kingdom", cc: "GB", currency: "GBP" },
  { name: "NASDAQ Stock Market", _id: "NASDAQ", country: "USA", cc: "USA", currency: "USD" },
  { name: "New York Stock Exchange", _id: "NYSE", country: "USA", cc: "USA", currency: "USD" },
  { name: "OTC Markets", _id: "OTC", country: "USA", cc: "USA", currency: "USD" },
  { name: "Caracas Stock Exchange", _id: "BVC", country: "Venezuela", cc: "VEN", currency: "VES" },
];

