import * as yup from "yup";

const yString = yup.string();
const pass_error_msg = `Password should contain atleast one uppercase, one lowercase alphabet, one special character and one number.`;

export const labelClassName = "form-label";

export const LoginSchema = yup.object().shape({
  email: yString.email("Invalid email address").required("Email is required!"),
  password: yString.required("Password is required!"),
});

export const ForgotPasswordSchema = yup.object().shape({
  email: yString.email("Invalid email address").required("Email is required!"),
});

export const ResetPasswordSchema = yup.object().shape({
  password: yString
    .required("New Password is required!")
    .min(8, "Password should be of min 8 chars")
    .max(15, "Password should contain max of 15 chars")
    .matches(/^(?=.{8,15}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$/, {
      message: pass_error_msg,
    }),
  confirmPassword: yString
    .required("Confirm Password is required!")
    .oneOf([yup.ref("password")], "Password must match"),
});

const lazyValidation = (value, message, isNumber = false, isAmount = false, options = {}) => {
  if (value || value === "") {
    return options.max
      ? yString.required(message).max(options.max, "Value should not be more than ${max} chars")
      : yString.required(message);
  }

  return yup.mixed().notRequired();
};

export const RegisterSchema = yup.object().shape({
  name: yString.required("Name is required!").max(50, "Name must be at most 50 charachters."),
  email: yString.email("Invalid email address").required("Email is required!"),
  country: yup.lazy((value) => lazyValidation(value, "Country is required")),
  password: yString
    .required("New Password is required!")
    .min(8, "Password should be of min 8 chars")
    .max(15, "Password should contain max of 15 chars")
    .matches(/^(?=.{8,15}$)(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W).*$/, {
      message: pass_error_msg,
    }),
  confirmPassword: yString
    .required("Confirm Password is required!")
    .oneOf([yup.ref("password")], "Password must match"),
  terms: yup
    .boolean()
    .oneOf([true], "You must accept the terms and conditions") // Checkbox must be checked
    .required("You must accept the terms and conditions"),
});

export const registerDefaultValues = {
  name: "",
  email: "",
  password: "",
  confirmPassword: "",
  terms: false,
  country: "",
};

export const captchaKey = process.env.REACT_APP_CAPTCHA_KEY;

export const countries_list = [
  { _id: "afghanistan", name: "Afghanistan" },
  { _id: "aland", name: "Aland" },
  { _id: "albania", name: "Albania" },
  { _id: "algeria", name: "Algeria" },
  { _id: "american_samoa", name: "American Samoa" },
  { _id: "andorra", name: "Andorra" },
  { _id: "angola", name: "Angola" },
  { _id: "anguilla", name: "Anguilla" },
  { _id: "antarctica", name: "Antarctica" },
  { _id: "antigua_and_barbuda", name: "Antigua and Barbuda" },
  { _id: "argentina", name: "Argentina" },
  { _id: "armenia", name: "Armenia" },
  { _id: "aruba", name: "Aruba" },
  { _id: "australia", name: "Australia" },
  { _id: "austria", name: "Austria" },
  { _id: "azerbaijan", name: "Azerbaijan" },
  { _id: "bahamas", name: "Bahamas" },
  { _id: "bahrain", name: "Bahrain" },
  { _id: "bangladesh", name: "Bangladesh" },
  { _id: "barbados", name: "Barbados" },
  { _id: "belarus", name: "Belarus" },
  { _id: "belgium", name: "Belgium" },
  { _id: "belize", name: "Belize" },
  { _id: "benin", name: "Benin" },
  { _id: "bermuda", name: "Bermuda" },
  { _id: "bhutan", name: "Bhutan" },
  { _id: "bolivia", name: "Bolivia" },
  { _id: "bonaire", name: "Bonaire" },
  { _id: "bosnia_and_herzegovina", name: "Bosnia and Herzegovina" },
  { _id: "botswana", name: "Botswana" },
  { _id: "bouvet_island", name: "Bouvet Island" },
  { _id: "brazil", name: "Brazil" },
  { _id: "british_indian_ocean_territory", name: "British Indian Ocean Territory" },
  { _id: "british_virgin_islands", name: "British Virgin Islands" },
  { _id: "brunei", name: "Brunei" },
  { _id: "bulgaria", name: "Bulgaria" },
  { _id: "burkina_faso", name: "Burkina Faso" },
  { _id: "burundi", name: "Burundi" },
  { _id: "cambodia", name: "Cambodia" },
  { _id: "cameroon", name: "Cameroon" },
  { _id: "canada", name: "Canada" },
  { _id: "cape_verde", name: "Cape Verde" },
  { _id: "cayman_islands", name: "Cayman Islands" },
  { _id: "central_african_republic", name: "Central African Republic" },
  { _id: "chad", name: "Chad" },
  { _id: "chile", name: "Chile" },
  { _id: "china", name: "China" },
  { _id: "christmas_island", name: "Christmas Island" },
  { _id: "cocos_(keeling)_islands", name: "Cocos (Keeling) Islands" },
  { _id: "colombia", name: "Colombia" },
  { _id: "comoros", name: "Comoros" },
  { _id: "cook_islands", name: "Cook Islands" },
  { _id: "costa_rica", name: "Costa Rica" },
  { _id: "croatia", name: "Croatia" },
  { _id: "cuba", name: "Cuba" },
  { _id: "curacao", name: "Curacao" },
  { _id: "cyprus", name: "Cyprus" },
  { _id: "czech_republic", name: "Czech Republic" },
  { _id: "democratic_republic_of_the_congo", name: "Democratic Republic of the Congo" },
  { _id: "denmark", name: "Denmark" },
  { _id: "djibouti", name: "Djibouti" },
  { _id: "dominica", name: "Dominica" },
  { _id: "dominican_republic", name: "Dominican Republic" },
  { _id: "east_timor", name: "East Timor" },
  { _id: "ecuador", name: "Ecuador" },
  { _id: "egypt", name: "Egypt" },
  { _id: "el_salvador", name: "El Salvador" },
  { _id: "equatorial_guinea", name: "Equatorial Guinea" },
  { _id: "eritrea", name: "Eritrea" },
  { _id: "estonia", name: "Estonia" },
  { _id: "eswatini", name: "Eswatini" },
  { _id: "ethiopia", name: "Ethiopia" },
  { _id: "falkland_islands", name: "Falkland Islands" },
  { _id: "faroe_islands", name: "Faroe Islands" },
  { _id: "fiji", name: "Fiji" },
  { _id: "finland", name: "Finland" },
  { _id: "france", name: "France" },
  { _id: "french_guiana", name: "French Guiana" },
  { _id: "french_polynesia", name: "French Polynesia" },
  { _id: "french_southern_territories", name: "French Southern Territories" },
  { _id: "gabon", name: "Gabon" },
  { _id: "gambia", name: "Gambia" },
  { _id: "georgia", name: "Georgia" },
  { _id: "germany", name: "Germany" },
  { _id: "ghana", name: "Ghana" },
  { _id: "gibraltar", name: "Gibraltar" },
  { _id: "greece", name: "Greece" },
  { _id: "greenland", name: "Greenland" },
  { _id: "grenada", name: "Grenada" },
  { _id: "guadeloupe", name: "Guadeloupe" },
  { _id: "guam", name: "Guam" },
  { _id: "guatemala", name: "Guatemala" },
  { _id: "guernsey", name: "Guernsey" },
  { _id: "guinea", name: "Guinea" },
  { _id: "guinea-bissau", name: "Guinea-Bissau" },
  { _id: "guyana", name: "Guyana" },
  { _id: "haiti", name: "Haiti" },
  { _id: "heard_island_and_mcdonald_islands", name: "Heard Island and McDonald Islands" },
  { _id: "honduras", name: "Honduras" },
  { _id: "hong_kong", name: "Hong Kong" },
  { _id: "hungary", name: "Hungary" },
  { _id: "iceland", name: "Iceland" },
  { _id: "india", name: "India" },
  { _id: "indonesia", name: "Indonesia" },
  { _id: "iran", name: "Iran" },
  { _id: "iraq", name: "Iraq" },
  { _id: "ireland", name: "Ireland" },
  { _id: "isle_of_man", name: "Isle of Man" },
  { _id: "israel", name: "Israel" },
  { _id: "italy", name: "Italy" },
  { _id: "ivory_coast", name: "Ivory Coast" },
  { _id: "jamaica", name: "Jamaica" },
  { _id: "japan", name: "Japan" },
  { _id: "jersey", name: "Jersey" },
  { _id: "jordan", name: "Jordan" },
  { _id: "kazakhstan", name: "Kazakhstan" },
  { _id: "kenya", name: "Kenya" },
  { _id: "kiribati", name: "Kiribati" },
  { _id: "kosovo", name: "Kosovo" },
  { _id: "kuwait", name: "Kuwait" },
  { _id: "kyrgyzstan", name: "Kyrgyzstan" },
  { _id: "laos", name: "Laos" },
  { _id: "latvia", name: "Latvia" },
  { _id: "lebanon", name: "Lebanon" },
  { _id: "lesotho", name: "Lesotho" },
  { _id: "liberia", name: "Liberia" },
  { _id: "libya", name: "Libya" },
  { _id: "liechtenstein", name: "Liechtenstein" },
  { _id: "lithuania", name: "Lithuania" },
  { _id: "luxembourg", name: "Luxembourg" },
  { _id: "macao", name: "Macao" },
  { _id: "madagascar", name: "Madagascar" },
  { _id: "malawi", name: "Malawi" },
  { _id: "malaysia", name: "Malaysia" },
  { _id: "maldives", name: "Maldives" },
  { _id: "mali", name: "Mali" },
  { _id: "malta", name: "Malta" },
  { _id: "marshall_islands", name: "Marshall Islands" },
  { _id: "martinique", name: "Martinique" },
  { _id: "mauritania", name: "Mauritania" },
  { _id: "mauritius", name: "Mauritius" },
  { _id: "mayotte", name: "Mayotte" },
  { _id: "mexico", name: "Mexico" },
  { _id: "micronesia", name: "Micronesia" },
  { _id: "moldova", name: "Moldova" },
  { _id: "monaco", name: "Monaco" },
  { _id: "mongolia", name: "Mongolia" },
  { _id: "montenegro", name: "Montenegro" },
  { _id: "montserrat", name: "Montserrat" },
  { _id: "morocco", name: "Morocco" },
  { _id: "mozambique", name: "Mozambique" },
  { _id: "myanmar_(burma)", name: "Myanmar (Burma)" },
  { _id: "namibia", name: "Namibia" },
  { _id: "nauru", name: "Nauru" },
  { _id: "nepal", name: "Nepal" },
  { _id: "netherlands", name: "Netherlands" },
  { _id: "new_caledonia", name: "New Caledonia" },
  { _id: "new_zealand", name: "New Zealand" },
  { _id: "nicaragua", name: "Nicaragua" },
  { _id: "niger", name: "Niger" },
  { _id: "nigeria", name: "Nigeria" },
  { _id: "niue", name: "Niue" },
  { _id: "norfolk_island", name: "Norfolk Island" },
  { _id: "north_korea", name: "North Korea" },
  { _id: "north_macedonia", name: "North Macedonia" },
  { _id: "northern_mariana_islands", name: "Northern Mariana Islands" },
  { _id: "norway", name: "Norway" },
  { _id: "oman", name: "Oman" },
  { _id: "pakistan", name: "Pakistan" },
  { _id: "palau", name: "Palau" },
  { _id: "palestine", name: "Palestine" },
  { _id: "panama", name: "Panama" },
  { _id: "papua_new_guinea", name: "Papua New Guinea" },
  { _id: "paraguay", name: "Paraguay" },
  { _id: "peru", name: "Peru" },
  { _id: "philippines", name: "Philippines" },
  { _id: "pitcairn_islands", name: "Pitcairn Islands" },
  { _id: "poland", name: "Poland" },
  { _id: "portugal", name: "Portugal" },
  { _id: "puerto_rico", name: "Puerto Rico" },
  { _id: "qatar", name: "Qatar" },
  { _id: "republic_of_the_congo", name: "Republic of the Congo" },
  { _id: "reunion", name: "Reunion" },
  { _id: "romania", name: "Romania" },
  { _id: "russia", name: "Russia" },
  { _id: "rwanda", name: "Rwanda" },
  { _id: "saint_barthelemy", name: "Saint Barthelemy" },
  { _id: "saint_helena", name: "Saint Helena" },
  { _id: "saint_kitts_and_nevis", name: "Saint Kitts and Nevis" },
  { _id: "saint_lucia", name: "Saint Lucia" },
  { _id: "saint_martin", name: "Saint Martin" },
  { _id: "saint_pierre_and_miquelon", name: "Saint Pierre and Miquelon" },
  { _id: "saint_vincent_and_the_grenadines", name: "Saint Vincent and the Grenadines" },
  { _id: "samoa", name: "Samoa" },
  { _id: "san_marino", name: "San Marino" },
  { _id: "sao_tome_and_principe", name: "Sao Tome and Principe" },
  { _id: "saudi_arabia", name: "Saudi Arabia" },
  { _id: "senegal", name: "Senegal" },
  { _id: "serbia", name: "Serbia" },
  { _id: "seychelles", name: "Seychelles" },
  { _id: "sierra_leone", name: "Sierra Leone" },
  { _id: "singapore", name: "Singapore" },
  { _id: "sint_maarten", name: "Sint Maarten" },
  { _id: "slovakia", name: "Slovakia" },
  { _id: "slovenia", name: "Slovenia" },
  { _id: "solomon_islands", name: "Solomon Islands" },
  { _id: "somalia", name: "Somalia" },
  { _id: "south_africa", name: "South Africa" },
  { _id: "south_georgia_and_the_south_sandwich_islands", name: "South Georgia and the South Sandwich Islands" },
  { _id: "south_korea", name: "South Korea" },
  { _id: "south_sudan", name: "South Sudan" },
  { _id: "spain", name: "Spain" },
  { _id: "sri_lanka", name: "Sri Lanka" },
  { _id: "sudan", name: "Sudan" },
  { _id: "suriname", name: "Suriname" },
  { _id: "svalbard_and_jan_mayen", name: "Svalbard and Jan Mayen" },
  { _id: "sweden", name: "Sweden" },
  { _id: "switzerland", name: "Switzerland" },
  { _id: "syria", name: "Syria" },
  { _id: "taiwan", name: "Taiwan" },
  { _id: "tajikistan", name: "Tajikistan" },
  { _id: "tanzania", name: "Tanzania" },
  { _id: "thailand", name: "Thailand" },
  { _id: "togo", name: "Togo" },
  { _id: "tokelau", name: "Tokelau" },
  { _id: "tonga", name: "Tonga" },
  { _id: "trinidad_and_tobago", name: "Trinidad and Tobago" },
  { _id: "tunisia", name: "Tunisia" },
  { _id: "turkey", name: "Turkey" },
  { _id: "turkmenistan", name: "Turkmenistan" },
  { _id: "turks_and_caicos_islands", name: "Turks and Caicos Islands" },
  { _id: "tuvalu", name: "Tuvalu" },
  { _id: "u.s._minor_outlying_islands", name: "U.S. Minor Outlying Islands" },
  { _id: "u.s._virgin_islands", name: "U.S. Virgin Islands" },
  { _id: "uganda", name: "Uganda" },
  { _id: "ukraine", name: "Ukraine" },
  { _id: "united_arab_emirates", name: "United Arab Emirates" },
  { _id: "united_kingdom", name: "United Kingdom" },
  { _id: "united_states", name: "United States" },
  { _id: "uruguay", name: "Uruguay" },
  { _id: "uzbekistan", name: "Uzbekistan" },
  { _id: "vanuatu", name: "Vanuatu" },
  { _id: "vatican_city", name: "Vatican City" },
  { _id: "venezuela", name: "Venezuela" },
  { _id: "vietnam", name: "Vietnam" },
  { _id: "wallis_and_futuna", name: "Wallis and Futuna" },
  { _id: "western_sahara", name: "Western Sahara" },
  { _id: "yemen", name: "Yemen" },
  { _id: "zambia", name: "Zambia" },
  { _id: "zimbabwe", name: "Zimbabwe" },
];

